import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {io} from 'socket.io-client';
import './styles.css';

const socket=io(window.location.origin,{autoConnect:false});
const prompts=['something you would pack for Mars','a food you could eat every day','something that makes a great gift','an object found in a classroom','something you would take camping','a useful kitchen object','something that belongs in a backpack','an object you would save in a fire'];

function App(){
 const [connected,setConnected]=useState(false),[screen,setScreen]=useState('home'),[name,setName]=useState(''),[room,setRoom]=useState(''),[game,setGame]=useState(null),[answer,setAnswer]=useState(''),[error,setError]=useState('');
 useEffect(()=>{socket.connect(); socket.on('connect',()=>setConnected(true));socket.on('disconnect',()=>setConnected(false));
  socket.on('room:update',setGame); socket.on('game:update',setGame); socket.on('game:error',e=>setError(e));
  socket.on('game:started',g=>{setGame(g);setScreen('game')}); socket.on('game:over',g=>{setGame(g);setScreen('results')});
  return()=>{socket.off();socket.disconnect()};},[]);
 const me=useMemo(()=>game?.players?.find(p=>p.id===socket.id),[game]);
 const create=()=>{if(!name.trim())return setError('Enter your name.');socket.emit('room:create',{name:name.trim()},r=>{if(r?.ok){setRoom(r.code);setGame(r.game);setScreen('lobby')}else setError(r?.error||'Could not create room.')})};
 const join=()=>{if(!name.trim()||!room.trim())return setError('Enter your name and room code.');socket.emit('room:join',{name:name.trim(),code:room.trim().toUpperCase()},r=>{if(r?.ok){setGame(r.game);setScreen('lobby')}else setError(r?.error||'Could not join room.')})};
 const start=()=>socket.emit('game:start',{code:game.code},r=>{if(!r?.ok)setError(r?.error||'Cannot start.')});
 const submit=()=>{if(!answer.trim()||!game)return;socket.emit('game:answer',{code:game.code,answer:answer.trim()});setAnswer('')};
 const pass=()=>{if(game)socket.emit('game:pass',{code:game.code})};
 if(screen==='home')return <div className="page"><header><div className="logo">🥔 <span>PASS!</span></div><div className={connected?'online':'offline'}>● {connected?'LIVE':'CONNECTING'}</div></header><main className="hero"><div className="badge">LIVE MULTIPLAYER · 5 ROUNDS</div><h1>Pass the potato.<br/><em>Beat the timer.</em></h1><p>A fast, chaotic party game for phones. Answer the prompt, pass the potato, and never be holding it when time runs out.</p><div className="cards"><section className="panel"><h2>Create a game</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><button onClick={create}>Create room →</button></section><section className="panel"><h2>Join a game</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><input value={room} onChange={e=>setRoom(e.target.value)} placeholder="Room code" maxLength="6"/><button className="secondary" onClick={join}>Join room →</button></section></div>{error&&<div className="error">{error}</div>}<div className="rules"><span>01</span><b>ANSWER</b><span>→</span><span>02</span><b>PASS</b><span>→</span><span>03</span><b>DON'T GET CAUGHT</b></div></main></div>;
 if(screen==='lobby')return <div className="page"><header><div className="logo">🥔 <span>PASS!</span></div><button className="ghost" onClick={()=>location.reload()}>Leave</button></header><main className="lobby"><div className="roomcode"><small>ROOM CODE</small><strong>{game.code}</strong><button onClick={()=>navigator.clipboard?.writeText(game.code)}>Copy</button></div><h1>Waiting for players</h1><p>Share the room code. Minimum 2 players.</p><div className="players">{game.players.map((p,i)=><div className="player" key={p.id}><div className="avatar">{p.name[0]?.toUpperCase()}</div><div><b>{p.name}</b>{i===0&&<small>HOST</small>}</div></div>)}</div>{game.players.length>=2?<button className="bigbtn" onClick={start}>Start game →</button>:<div className="waiting">Waiting for at least 2 players…</div>}{error&&<div className="error">{error}</div>}</main></div>;
 if(screen==='game'&&game){const pct=Math.max(0,(game.timeLeft/game.duration)*100);return <div className="game"><header><div className="logo">🥔 <span>PASS!</span></div><div className="round">ROUND {game.round}/5</div><div className="scores">{game.players.map(p=><span key={p.id} className={p.id===game.holderId?'holding':''}>{p.name}: {p.score}</span>)}</div></header><main><div className="timer" style={{'--pct':pct+'%'}}><div><small>TIME</small><strong>{game.timeLeft.toFixed(1)}</strong></div></div><div className="potato">🥔</div><div className="turn">{game.holderId===socket.id?'YOU HAVE THE POTATO':'POTATO IS MOVING'}</div><h1>Give me <em>{game.prompt}</em></h1><div className="answer"><input disabled={game.holderId!==socket.id} value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder={game.holderId===socket.id?'Type an answer…':'Wait for the potato…'}/><button disabled={game.holderId!==socket.id||!answer.trim()} onClick={submit}>Answer</button></div><button className="pass" disabled={game.holderId!==socket.id||!game.hasAnswered} onClick={pass}>PASS THE POTATO →</button><p className="hint">{game.holderId===socket.id?(game.hasAnswered?'Now pass it!':'Answer first, then pass.'):'Watch the timer — whoever holds it at zero gets a point.'}</p></main></div>}
 if(screen==='results'&&game)return <div className="page"><header><div className="logo">🥔 <span>PASS!</span></div></header><main className="results"><div className="badge">GAME OVER</div><h1>Final scores</h1><p>Lowest score wins after 5 rounds.</p><div className="scoreboard">{[...game.players].sort((a,b)=>a.score-b.score).map((p,i)=><div className="score" key={p.id}><span>#{i+1}</span><b>{p.name}</b><strong>{p.score}</strong></div>)}</div><button className="bigbtn" onClick={()=>location.reload()}>Play again</button></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
